const ActionType = {
  SELECT_ITEM: "SELECT_ITEM",
  UNSELECT_ITEM: "UNSELECT_ITEM",
  SET_QTY_STOCK_IN: "SET_QTY_STOCK_IN",
  SET_ITEM_BY_LOCATION: "SET_ITEM_BY_LOCATION",
  UNSET_ITEM_BY_LOCATION: "UNSET_ITEM_BY_LOCATION",
  SET_NAME: "SET_NAME",
  SET_DETAIL_ITEM: "SET_DETAIL_ITEM",
  UN_SET_DETAIL_ITEM: "UN_SET_DETAIL_ITEM",
  SET_LOCATION_BY_ITEM: "SET_LOCATION_BY_ITEM",
  SET_HISTORY_BY_LOCATION: "SET_HISTORY_BY_LOCATION",
  SET_SHOW_ITEMS: "SET_SHOW_ITEMS",
  SET_DETAIL_HISTORY: "SET_DETAIL_HISTORY",
  SET_FROM_LOCIDX: "SET_FROM_LOCIDX",
  SET_LIST_HISTORIES: "SET_LIST_HISTORIES",
  SET_USEFORM_LIST_HISTORIES: "SET_USEFORM_LIST_HISTORIES",
  SET_USEFORM_DATE_STOCK_MISSING: "SET_USEFORM_DATE_STOCK_MISSING",
  SET_MENU: "SET_MENU",
  SET_PROFILE: "SET_PROFILE",
  SET_SELECT_ITEM_BUNDLE: "SET_SELECT_ITEM_BUNDLE",
  SET_SELECT_ITEM_PURCHASE: "SET_SELECT_ITEM_PURCHASE",
  SET_SELECT_ITEM_MIX_BUNDLE: "SET_SELECT_ITEM_MIX_BUNDLE",
  SET_EDIT_DATA_PURCHASE:"SET_EDIT_DATA_PURCHASE",
  SET_EDIT_DATA_SALES:"SET_EDIT_DATA_SALES",
  SET_EDIT_ITEM_BUNDLE: "SET_EDIT_ITEM_BUNDLE"
};

export default ActionType;
